# Custom Language File for Launcher Customizer

[ejs.app]
title = "행복 놀이동산"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/happ"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
mediaAfreecaTVURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/happ"
supportLink = "https://github.com/CustomLauncherLab/happ/issues"

[ejs.welcome]
welcomeHeader = "행복 놀이동산"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."